version: '3.8'
services:
  db:
    hostname: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - '5432'
    env_file:
      - '.env'
    networks:
      - local
    
    
  # authapp:
  #   build: .
  #   hostname: authapp
  #   depends_on:
  #     db:
  #       condition: service_completed_successfully
  #   ports:
  #     - "3000:3000"
  #     - '5432:5432'
  #   restart: always
  #   env_file:
  #     - '.env'
  #   networks:
  #     - local

networks:
  local:
    driver: bridge
   
volumes:
  db:
    driver: local